config/routes.rb
Rails.application.routes.draw do
  authenticated :user do
    root :to => 'posts#index', as: :authenticated_root
  end
  root :to => 'pages#home'
  get 'friendships/create'

  devise_for :users, :controllers => { registrations: 'registrations', :omniauth_callbacks => "users/omniauth_callbacks" }
  
  resources :users, only: %i[new create index show]
  get 'users_index', to: 'users#index'
  
  resources :posts, only: %i[new create index show edit update]
  get 'posts_index', to: 'posts#index'
  match '/posts/create', to: 'posts#create', via: :post, as: :create_post
  delete '/posts/destroy/:id', to: 'posts#destroy', as: :destroy_post

  match '/likes/create/:id', to: 'likes#create', via: :post, as: :create_like
  delete '/likes/destroy/:id', to: 'likes#destroy', as: :destroy_like

  get 'comments/new'
  match '/comments/create/:id', to: 'comments#create', via: :post, as: :create_comment

  resources :friendships, only: %i[create destroy]
  match '/friendships/update_status/:id', to: 'friendships#update_status', via: :post, as: :update_status
end

app/models/user.rb
# frozen_string_literal: true

class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :omniauthable, omniauth_providers: [:facebook]
  has_many :posts, foreign_key: :author_id, dependent: :destroy
  has_many :comments, foreign_key: :commenter_id, dependent: :destroy
  has_many :likes, dependent: :destroy
  has_many :friendships, dependent: :destroy
  has_many :inverse_friendships, class_name: 'Friendship', foreign_key: 'friend_id', dependent: :destroy

  has_many :confirmed, -> { where(confirmed: true) }, class_name: 'Friendship'
  has_many :friends, through: :confirmed

  has_many :pending_friendships, ->(user) { where(confirmed: nil, user: user) }, class_name: 'Friendship',
                                                                                 foreign_key: 'user_id'
  has_many :inverted_pending, ->(user) { where(confirmed: nil, friend: user) }, class_name: 'Friendship',
                                                                                foreign_key: 'friend_id'

  validates :name, presence: true, length: { minimum: 3, maximum: 50 }
  validates :lastname, presence: true, length: { minimum: 3, maximum: 50 }
  validates :password, presence: true, length: { minimum: 6, maximum: 30 }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i.freeze
  validates :email, presence: true, length: { maximum: 255 },
                    format: { with: VALID_EMAIL_REGEX }, uniqueness: { case_sensitive: false }

  before_save :downcase_email

  def downcase_email
    email.downcase!
  end

  def news_feed
    a = Post.where(author: friends + [self]).mine_and_friends(self)
    b = Post.where(author: friends + [self]).recent_posts
    c = a + b
    c.uniq!
  end

  def self.new_with_session(params, session)
    super.tap do |user|
      if (data = session['devise.facebook_data'] && session['devise.facebook_data']['extra']['raw_info'])
        user.email = data['email'] if user.email.blank?
      end
    end
  end

  def self.from_omniauth(auth)
    where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
      user.email = auth.info.email
      user.password = Devise.friendly_token[0, 20]
      user.name = auth.info.name.split(' ')[0]
      user.lastname = auth.info.name.split[1..-1].join(' ')
      user.image = auth.info.image
      user.save!
    end
  end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  def facebook
    @user = User.from_omniauth(request.env['omniauth.auth'])
    if @user.persisted?
      sign_in_and_redirect @user, event: :authentication
      set_flash_message(:notice, :success, kind: 'Facebook') if is_navigational_format?
    else
      session['devise.facebook_data'] = request.env['omniauth.auth']
      redirect_to new_user_registration_url
    end
  end

  def failure
    redirect_to root_path
  end
end

app/controllers/users_controller.rb
# frozen_string_literal: true

class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
  end

  def index
    @users = User.all
    @post = Post.new
    @pending_requests = current_user.inverted_pending
  end

  def show
    @post = Post.new
    @user = User.find_by_id(params[:id])
    @is_pending = current_user.friendships.is_a_pending(@user).exists?
    @is_incoming = @user.friendships.is_a_pending(current_user).exists?
    @same_profile = @user == current_user
    @already_friends = current_user.friendships.is_my_friend?(@user).exists?
    @pending_requests = current_user.inverted_pending
  end

  private

  def user_params
    params.require(:user).permit(:name, :lastname, :email, :password)
  end
end

app/helpers/users_helper.rb
# frozen_string_literal: true

module UsersHelper
end

app/views/users/index.html.erb
<div class="ui container">
  <h2 class="ui center aligned header">
      Users Index 
      <i class="ui envelope open outline icon"></i>
  </h2>
</div>
<br>
<div class="centered aligned">
<% @users.each do |user|%>
  <div class="ui raised segment">
    <div class="content">
    <%= link_to user_path(user) do %>
      <div class="header"><%=user.name%> <%=user.lastname%></div>
    <%end%>
      <small style="color: grey"><%=user.email%></small>
      <br>
      <% if !current_user.friends.include?(user) && user != current_user && current_user.pending_friendships.find_by(friend: user).nil? && current_user.inverted_pending.find_by(user: user).nil? %>
        <%= link_to friendships_create_path(friend_id: user) do %>
          <button class="mini ui button">Add friend</button>
        <% end %>
      <% end %>
    </div>
  </div>
<%end%>
<%= render 'shared/columns'%>
<% content_for :right_side do %>
  <%= render 'shared/notif_bar'%>
<% end %>
</div>

app/views/users/show.html.erb
<div class="ui container">
  <h2 class="ui center aligned header">
    User Profile
    <i class="ui user outline icon"></i>
  </h2>
</div>
<div class="centered aligned">
  <% if current_user.friends.include?(@user) || current_user == @user %>

      <%= render "shared/postform", locals: { object: @user, from: 'user' } %>
    <% Post.mine_and_friends(@user).each do |post| %>
      <%= render 'shared/display_post', locals: {object: post, from: 'user', user: @user} %>
    <% end %>
  <% end %>

  <% content_for :left_side do %>
    <div class="ui card">
      <div class="image">
        <% if @user.image.nil? %>
          <%= image_tag('profile.jpg', alt: "profile-image") %>
        <% else %>
          <%= image_tag(@user.image, alt: "profile-image") %>
        <% end %>
      </div>
      <div class="content">
        <div class="header"><%= "#{@user.name} #{@user.lastname}" %></div>
        <div class="meta">
          <a><%= @user.email %></a>
        </div>
        <div class="description">
          Needs to fullfill
        </div>
      </div>
      <div class="extra content">
      <span class="right floated">
        Joined in <%= @user.created_at.year %>
      </span>
        <span>
        <i class="user icon"></i>
          <%= @user.friendships.confirmed.count %> Friends
      </span>
      </div>
      <% if @is_pending %>
        <div class="extra content">
          <div class="right floated">
            <p class="meta">Friend request sent</p>
          </div>
        </div>
      <% elsif @is_incoming %>
        <div class="extra content">
          <div class="right floated">
            <p class="meta"><%= @user.name %> sent you a friend request</p>
          </div>
        </div>
      <% elsif @same_profile || @already_friends %>
        <div></div>
      <% else %>
        <%= link_to friendships_create_path(friend_id: @user) do %>
          <div class="ui bottom attached button">
            <i class="add icon"></i>
            Add Friend
          </div>
        <% end %>
      <% end %>
    </div>
    <br>
    <% if !@user.friends.empty? %>
      <div class="ui card">
        <div class="ui middle aligned selection divided list">
          <% @user.friends.each do |friend| %>
            <%= link_to user_path(friend.id), class: "item" do %>
              <% if friend.image.nil? %>
                <%= image_tag('profile.jpg', class: "ui avatar image", alt: "profile-image") %>
              <% else %>
                <%= image_tag(friend.image, class: "ui avatar image", alt: "profile-image") %>
              <% end %>
              <div class="content">
                <div class="ui header floated right"><%= friend.name %></div>
              </div>
            <% end %>
          <% end %>
        </div>
      </div>
    <% end %>
  <% end %>

  <% content_for :right_side do %>
    <%= render 'shared/notif_bar'%>
  <% end %>
</div>