config/routes.rb
Rails.application.routes.draw do
  authenticated :user do
    root :to => 'posts#index', as: :authenticated_root
  end
  root :to => 'pages#home'
  get 'friendships/create'

  devise_for :users, :controllers => { registrations: 'registrations', :omniauth_callbacks => "users/omniauth_callbacks" }
  
  resources :users, only: %i[new create index show]
  get 'users_index', to: 'users#index'
  
  resources :posts, only: %i[new create index show edit update]
  get 'posts_index', to: 'posts#index'
  match '/posts/create', to: 'posts#create', via: :post, as: :create_post
  delete '/posts/destroy/:id', to: 'posts#destroy', as: :destroy_post

  match '/likes/create/:id', to: 'likes#create', via: :post, as: :create_like
  delete '/likes/destroy/:id', to: 'likes#destroy', as: :destroy_like

  get 'comments/new'
  match '/comments/create/:id', to: 'comments#create', via: :post, as: :create_comment

  resources :friendships, only: %i[create destroy]
  match '/friendships/update_status/:id', to: 'friendships#update_status', via: :post, as: :update_status
end

app/views/shared/_check_likes.html.erb
<%if liked?(locals[:post])%>
  <%= link_to create_like_path(locals[:post], from: locals[:from], user: locals[:user]), method: :post do %>
    <i class="heart grey like icon"></i>
  <% end %>
<%else%>
  <%= link_to destroy_like_path(locals[:post], from: locals[:from], user: locals[:user]), method: :delete do %>
    <i class="heart teal like icon"></i>
  <% end %>
<%end%>

app/views/shared/_columns.html.erb
<% content_for :right_side do %>
<div class="container">
</div>
<% end %>
<% content_for :left_side do %>
<br>
<div class="container">
  <%= render 'shared/links'%>
</div>
<% end %>

app/views/shared/_comment_form.html.erb
<div class="ui divided">
  <%= form_for(@comment, url: create_comment_path, :html => {:class => "ui form"}) do |f| %>
    <%= render "devise/shared/error_messages", resource: @comment %>

    <div class="ui fluid huge icon input">
      <%= f.text_field :content, placeholder: "Share your thoughts...", rows: 2 %>
      <i class="paper plane icon"></i>
    </div>
    <br>
  <% end %>
</div>

app/views/shared/_display_post.html.erb
<div class="ui raised segments">
  <div class="ui segment">
    <div class="ui horizontal list">
      <div class="item">
        <% if locals[:object].author.image.nil? %>
          <%= image_tag('profile.jpg', class: "ui avatar image", alt: "profile-image") %>
        <% else %>
          <%= image_tag(locals[:object].author.image, class: "ui avatar image", alt: "profile-image") %>
        <% end %>
        <div class="content">
          <%= link_to user_path(locals[:object].author) do %>
            <% if locals[:object].author != locals[:object].friend %>
              <div class="ui sub header"><%= "#{locals[:object].author.name} #{locals[:object].author.lastname}" %>
                <i class="angle right icon" style="margin: 0 7px 0 7px"></i>
                <%= "#{locals[:object].friend.name} #{locals[:object].friend.lastname}" %>
              </div>
            <% else %>
              <div class="ui sub header"><%= "#{locals[:object].author.name} #{locals[:object].author.lastname}" %></div>
            <% end %>
          <% end %>
          <small style="color: grey"><%= time_ago_in_words(locals[:object].created_at, include_seconds: true).gsub('about', '') %></small>
        </div>
      </div>
    </div>
  </div>
  <div class="ui segment">
    <div class="content">
      <%= simple_format(locals[:object].content) %>
    </div>
  </div>
  <div class="ui segment card">
    <div class="content">
      <span class="left floated">
        <% if locals[:from] == 'user' %>
          <%= render 'shared/check_likes', locals: {post: locals[:object], from: locals[:from], user: locals[:user]} %>
        <% else %>
          <%= render 'shared/check_likes', locals: {post: locals[:object], from: locals[:from]} %>
        <% end %>

        <small class="meta"> <%= "  #{locals[:object].likes.count} likes" %></small>
      </span>
      <span class="right floated">
        <i class="comment teal outline icon"></i>
        <small class="meta right floated"><%= locals[:object].comments.count %> comments</small>
      </span>
    </div>
    <%= link_to post_path(locals[:object]) do %>
      <div class="ui bottom attached button">
        <i class="envelope outline icon"></i>
        Open
      </div>
    <% end %>
  </div>
</div>

app/views/shared/_links.html.erb
<div class="ui centered grid">
  <div class="ui secondary vertical text menu">
    <div class="item">
      <%= link_to posts_index_path do %>
        <button class="ui basic teal button">
          <i class="home icon"></i>
          Home
        </button>
      <% end %>
    </div>
    <div class="item">
      <%= link_to users_index_path do %>
        <button class="ui basic teal button">
          <i class="users icon"></i>
          Users
        </button>
      <% end %>
    </div>
  </div>
</div>

app/views/shared/_navigation.html.erb
<a class="item" style="padding: 0px">
  <%= link_to posts_path do %>
    <div class="logo"></div>
  <% end %>
</a>
<% if current_user.nil?%>
  <%= render 'shared/signin_form' %>
<%else%>
  <%= render 'shared/signout_nav'%>
<%end%>

app/views/shared/_notif_bar.html.erb
<div class="ui card">
  <div class="content">
    <%= link_to user_path(current_user) do %>
      <h3 class="ui header" style="
      margin-top: 0px">
        <i class="bell outline icon floated right"></i>
        <div class="content">Welcome <%= current_user.name %>!</div>
      </h3>
    <% end %>
    <br>
    <div class="comments">
      <i class="comment icon"></i>
      <strong>Recents comments on your posts:</strong>
      <br>
      <br>
      <% if current_user.posts.empty? %>
        <div class="ui center aligned">No recent comments</div>
      <% else %>
        <% current_user.posts.last_five_posts.each do |post| %>
          <% unless post.comments.size.zero? %>
            <%= link_to post_path(post) do %>
              <div><%= post.comments.last.content %></div>
              <div class="ui fitted divider"></div>
            <% end %>
          <% end %>
        <% end %>
      <% end %>
    </div>
    <br>
    <% unless @pending_requests.empty? %>
      <div class="friend_requests">
        <i class="user icon"></i>
        <strong>Friends requests: </strong><%= @pending_requests.count %>
        <br>
        <br>
        <% @pending_requests.each do |friend_req| %>
          <div class="ui equal width form">
            <div class="ui equal width form">
              <div class="fields">
                <div class="field"><%= friend_req.user.name %> <%= friend_req.user.lastname %></div>
                <div class="field">
                  <button class="mini positive ui button field" id="accept_friendship">
                    <%= link_to 'Accept', update_status_path(friend_request: friend_req), method: :post %>
                  </button>
                </div>
                <div class="field">
                  <button class="mini negative ui button field" id="decline_friendship">
                    <%= link_to 'Decline', friendship_path(id: friend_req, friend_id: friend_req.user), method: :delete %>
                  </button>
                </div>
              </div>
            </div>
            <div class="ui fitted divider"></div>
            <br>
        <% end %>
        </div>
    <% end %>
    </div>
  </div>
</div>

app/views/shared/_postform.html.erb
<br>
<%= form_for(@post, from: locals[:from], object: locals[:object], html: { class: "ui form" }) do |f| %>
  <%= render "devise/shared/error_messages", resource: @post %>
  <%= hidden_field_tag 'friend_id', locals[:object].id %>
  <%= hidden_field_tag 'from', locals[:from] %>
  <% if locals[:from] == 'index' %>
    <%= f.text_area :content, placeholder: "Write your post here...", style: "height: 30px" %>
  <% elsif locals[:from] == 'user' && locals[:object] != current_user %>
    <%= f.text_area :content, placeholder: "Write a post to #{locals[:object].name}", style: "height: 30px" %>
  <% else %>
    <%= f.text_area :content, placeholder: "Write your post here...", style: "height: 30px" %>
  <% end %>

  <br>
    <%= f.submit "Post", class: 'medium ui teal basic fluid button'%>
  <br>
<% end %>

app/views/shared/_signin_form.html.erb
<div class="right menu">
  <div class="ui inverted inline form relaxed">
    <div class="three fields" style="margin:0.5em 0.9em -0.9em">
      <%= form_for(resource, as: resource_name, url: session_path(resource_name), :html => {:class => "ui form row"}) do |f| %>
      <div class="ui equal width form">
        <div class="fields">
          <div class="field">
            <%= f.email_field :email, placeholder:'Email' %>
          </div>

          <div class="field">
            <%= f.password_field :password, placeholder:'Password' %>
          </div>

          <div class="actions">
            <%= f.submit "Log in", class: 'ui inverted teal basic button' %>
          </div>
          <br>
        </div>
      </div>
      <% end %>
    </div>
  </div>
</div>

app/views/shared/_signout_nav.html.erb
<div class="right menu">
  <div class="ui right floated field">
  </div>
  <div class="ui equal width form">
    <div class=" middle aligned content">
      <div class="header">
        <%= link_to user_path(current_user) do %>
          <p class="ui inverted teal item"><%= current_user.name %> | <%= current_user.email %></p>
        <% end %>
      </div>
    </div>
  </div>
  <div class="ui inverted inline form relaxed">
    <%= link_to destroy_user_session_path, method: :delete do %>
      <div class="ui inverted teal basic button" style="margin:0.5em 0.9em -0.9em">
        Sign out
      </div>
    <% end %>
  </div>
</div>

app/views/shared/_signup_form.html.erb
<h4 class="ui center aligned medium header">
  Sign up
</h4>
<br>
<div class="ui container centered grid">
  <%= form_for(resource, as: resource_name, url: registration_path(resource_name), :html => {:class => "ui form"}) do |f| %>
    <%= render "devise/shared/error_messages", resource: resource %>
    <div class="ten wide column">
      <div class="ui equal width form">
        <div class="fields">
          <div class="field">
            <%= f.text_field :name, placeholder: "Name" %>
          </div>
          <div class="field">
            <%= f.text_field :lastname, placeholder: "Lastname" %>
          </div>
        </div>
      </div>

      <div class="field">
        <%= f.email_field :email, placeholder: "Email" %>
      </div>

      <div class="field">
        <%= f.password_field :password, placeholder: "Password" %>
      </div>

      <div class="field">
        <%= f.password_field :password_confirmation, placeholder: "Confirm Password" %>
      </div>

      <div class="actions">
        <%= f.submit "Sign up", class: 'ui teal basic button' %>
      </div>
      <br>
    </div>
  <% end %>
</div>
<div class="ui horizontal divider">OR</div>
<br>
<% unless current_user %>
  <%= link_to user_facebook_omniauth_authorize_path do %>
    <div class="ui blue basic button container centered">
      <i class="facebook icon"></i> Continue with Facebook
    </div>
  <% end %>
<% end %>