config/routes.rb
Rails.application.routes.draw do
  authenticated :user do
    root :to => 'posts#index', as: :authenticated_root
  end
  root :to => 'pages#home'
  get 'friendships/create'

  devise_for :users, :controllers => { registrations: 'registrations', :omniauth_callbacks => "users/omniauth_callbacks" }
  
  resources :users, only: %i[new create index show]
  get 'users_index', to: 'users#index'
  
  resources :posts, only: %i[new create index show edit update]
  get 'posts_index', to: 'posts#index'
  match '/posts/create', to: 'posts#create', via: :post, as: :create_post
  delete '/posts/destroy/:id', to: 'posts#destroy', as: :destroy_post

  match '/likes/create/:id', to: 'likes#create', via: :post, as: :create_like
  delete '/likes/destroy/:id', to: 'likes#destroy', as: :destroy_like

  get 'comments/new'
  match '/comments/create/:id', to: 'comments#create', via: :post, as: :create_comment

  resources :friendships, only: %i[create destroy]
  match '/friendships/update_status/:id', to: 'friendships#update_status', via: :post, as: :update_status
end

app/models/post.rb
# frozen_string_literal: true

class Post < ApplicationRecord
  belongs_to :author, class_name: 'User'
  validates :author, presence: true

  belongs_to :friend, class_name: 'User'
  validates :friend, presence: true

  has_many :comments, dependent: :destroy
  has_many :likes, dependent: :destroy

  validates :content, presence: true, length: { minimum: 1, maximum: 500 }
  scope :recent_posts, -> { where('created_at < ?', Time.current).order(created_at: :DESC) }
  scope :mine_and_friends, ->(user) { where(friend_id: user).or(Post.where(author_id: user)).order(created_at: :DESC) }
  scope :last_five_posts, -> { where('created_at < ?', Time.current).order(created_at: :DESC).limit(5) }
end

app/controllers/post_controller.rb
class PostController < ApplicationController
  def new
    @post = Post.new
  end

  def create
    @post = Post.new(post_params)
  end

  def index
    @posts = Post.all
  end

  private

  def post_params
    params.require(:post).permit(:content, :author_id)
  end

end

app/controllers/posts_controller.rb
# frozen_string_literal: true

class PostsController < ApplicationController
  before_action :access_post, only: :edit
  def new
    @post = Post.new
  end

  def create
    @post = current_user.posts.build(post_params)
    @post.update(friend_id: params[:friend_id].to_i)
    if @post.save
      redirecting_data(params[:from], params[:friend_id].to_i) if params[:from] == 'user'
      redirecting_data(params[:from]) if params[:from] == 'index'
    else
      flash[:alert] = 'Something went wrong'
      render 'new'
    end
  end

  def index
    @posts = current_user.news_feed
    @post = Post.new
    @pending_requests = current_user.inverted_pending
  end

  def show
    @post = Post.find(params[:id])
    if current_user.friends.include?(@post.author) || current_user == @post.author
      @comment = Comment.new
      @index_comments = @post.comments.all.recent_comments
    else
      flash[:alert] = 'This post is inaccessible from your user.'
      redirect_to posts_path
    end
  end

  def edit
    @post = Post.find(params[:id])
  end

  def update
    @post = Post.find(params[:id])
    if @post.update_attributes(post_params)
      flash[:notice] = 'Post updated'
      redirect_to post_path(params[:id])
    else
      render 'edit'
    end
  end

  def destroy
    @post = Post.find(params[:id])
    if @post.destroy
      flash[:notice] = 'Post deleted'
    else
      flash[:alert] = 'Post cannot be deleted'
    end
    redirect_to posts_index_path
  end

  private

  def access_post
    post = current_user.posts.find_by(id: params[:id])
    if post.nil?
      flash[:alert] = 'You are not authorized to do this'
      render post_path(params[:id])
    else
      @post
    end
  end

  def authorized_viewer(user)
    current_user.friends.include?(user)
  end

  def post_params
    params.require(:post).permit(:content, :author_id, :friend_id)
  end

  def redirecting_data(from, user = nil)
    redirect_to posts_index_path if from == 'index'
    redirect_to user_path(user) if from == 'user'
  end
end

app/helpers/posts_helper.rb
# frozen_string_literal: true

module PostsHelper
  def post_owner?(post)
    current_user == post.author
  end
end

app/views/posts/edit.html.erb
<h2 class="ui center aligned icon header">
  <i class="circular teal edit outline icon"></i>
  Edit your post
</h2>
<br>
<div class="ui centered aligned">
  <div class="ui segments">
    <div class="ui segment">
      <div class="ui horizontal list">
        <div class="item">

          <% if @post.author.image.nil? %>
            <%= image_tag('profile.jpg', class: "ui avatar image", alt: "profile-image") %>
          <% else %>
            <%= image_tag(@post.author.image, class: "ui avatar image", alt: "profile-image") %>
          <% end %>
          <div class="content">
            <%= link_to user_path(@post.author) do %>
              <% if @post.author != @post.friend %>
                <div class="ui sub header"><%= "#{@post.author.name} #{@post.author.lastname}" %>
                  <i class="angle right icon" style="margin: 0 7px 0 7px"></i>
                  <%= "#{@post.friend.name} #{@post.friend.lastname}" %>
                </div>
              <% else %>
                <div class="ui sub header"><%= "#{@post.author.name} #{@post.author.lastname}" %></div>
              <% end %>
            <% end %>
            <small style="color: grey"><%= time_ago_in_words(@post.created_at, include_seconds: true).gsub('about', '') %></small>
          </div>
        </div>

      </div>
      <%= render "shared/postform", locals: {object: @post} %>
    </div>
  </div>
</div>

app/views/posts/index.html.erb
<div class="ui container">
  <h2 class="ui center aligned header">
    Post Index
    <i class="ui envelope open outline icon"></i>
  </h2>
</div>
<br>
<%= render "shared/postform", locals: { object: current_user, from: 'index' } %>
<br>
<div class="centered aligned">
  <% @posts.each do |post| %>
    <%= render 'shared/display_post', locals: { object: post, from: 'index'} %>
  <% end %>
  <br>
  <br>
  <%= render 'shared/columns' %>
  <br>
  <% content_for :right_side do %>
    <%= render 'shared/notif_bar'%>
  <% end %>
</div>

app/views/posts/show.html.erb
<div class="ui">
  <br/>
  <div class="ui container">
    <h2 class="ui center aligned header">
      Post
      <i class="ui envelope open outline icon"></i>
    </h2>

  </div>
  <div class="ui segments">
    <div class="ui segment">
      <div class="ui horizontal list">
        <div class="item">

          <% if @post.author.image.nil? %>
            <%= image_tag('profile.jpg', class: "ui avatar image", alt: "profile-image") %>
          <% else %>
            <%= image_tag(@post.author.image, class: "ui avatar image", alt: "profile-image") %>
          <% end %>
          <div class="content">
            <%= link_to user_path(@post.author) do %>
              <% if @post.author != @post.friend %>
                <div class="ui sub header"><%= "#{@post.author.name} #{@post.author.lastname}" %>
                  <i class="angle right icon" style="margin: 0 7px 0 7px"></i>
                  <%= "#{@post.friend.name} #{@post.friend.lastname}" %>
                </div>
              <% else %>
                <div class="ui sub header"><%= "#{@post.author.name} #{@post.author.lastname}" %></div>
              <% end %>
            <% end %>
            <small style="color: grey"><%= time_ago_in_words(@post.created_at, include_seconds: true).gsub('about', '') %></small>
          </div>
        </div>
      </div>
    </div>
    <div class="ui segment">
      <div class="content">
        <%= simple_format(@post.content) %>
        <% if post_owner?(@post) %>
          <%= link_to edit_post_path(@post) do %>
            <div class="ui bottom right attached mini label" style="padding-right: 50px">EDIT</div>
          <% end %>
          <%= link_to destroy_post_path(@post), method: :delete do %>
            <div class="ui bottom right attached mini label">DELETE</div>
          <% end %>
        <% end %>
      </div>
    </div>
    <div class="ui segment card">
      <div class="content">
        <span class="left floated">
          <%= render 'shared/check_likes', locals: {post: @post, from: 'show'} %>

          <small class="meta"> <%= "  #{@post.likes.count} likes" %></small>
        </span>
        <span class="right floated">
          <i class="comment teal outline icon"></i>
          <small class="meta right floated"><%= @post.comments.count %> comments</small>
        </span>
      </div>
    </div>
    <div class="ui segment">
      <%= render 'shared/comment_form' %>
    </div>
    <div class="ui accordion">
      <div class="ui title trigger attached button" tabindex="0">
        <i class="icon dropdown"></i>
        Comments
      </div>
      <div class="ui accordion-content">
        <br/>
        <% @index_comments.each do |comm| %>
          <div class="ui segment">
            <div class="ui grid">
              <div class="four wide column">
                <div class="ui horizontal list">
                  <div class="item">
                    <% if comm.commenter.image.nil? %>
                      <%= image_tag('profile.jpg', class: "ui avatar image", alt: "profile-image") %>
                    <% else %>
                      <%= image_tag(comm.commenter.image, class: "ui avatar image", alt: "profile-image") %>
                    <% end %>
                    <div class="content">
                      <%= link_to user_path(comm.commenter.id) do %>
                        <div class="ui sub header"><%= "#{comm.commenter.name} #{comm.commenter.lastname}" %></div>
                      <% end %>
                      <small style="color: grey"><%= time_ago_in_words(comm.created_at, include_seconds: true).gsub('about', '') %></small>
                    </div>
                  </div>
                </div>
              </div>
              <div class="twelve wide column">
                <div class="content">
                  <%= comm.content %>
                </div>
              </div>
            </div>
          </div>
        <% end %>
      </div>
    </div>
  </div>
  <%= render 'shared/columns' %>
</div>